import { Game } from '@/types';

export const mockGames: Game[] = [
  {
    id: 1,
    title: 'Elden Ring',
    genre: 'RPG',
    platform: 'PC',
    description: 'Open world action RPG',
  },
  {
    id: 2,
    title: 'Hollow Knight',
    genre: 'Metroidvania',
    platform: 'PC',
    description: 'Indie platformer in a dark fantasy world',
  },
  {
    id: 3,
    title: 'The Witcher 3',
    genre: 'RPG',
    platform: 'PC, PS4, Xbox',
    description: 'Story-driven RPG in an open world',
  },
  {
    id: 4,
    title: 'Stardew Valley',
    genre: 'Simulation',
    platform: 'PC, Switch',
    description: 'Farming and life simulation game',
  },
  {
    id: 5,
    title: 'Celeste',
    genre: 'Platformer',
    platform: 'PC, Switch',
    description: 'Precision platformer about climbing a mountain',
  },
  {
    id: 6,
    title: 'Hades',
    genre: 'Roguelike',
    platform: 'PC, Switch',
    description: 'Action-packed roguelike dungeon crawler',
  },
  {
    id: 7,
    title: 'Among Us',
    genre: 'Party',
    platform: 'PC, Mobile',
    description: 'Social deduction game',
  },
  {
    id: 8,
    title: 'Cyberpunk 2077',
    genre: 'RPG',
    platform: 'PC, PS4, Xbox',
    description: 'Futuristic open world RPG',
  },
  {
    id: 9,
    title: 'Minecraft',
    genre: 'Sandbox',
    platform: 'PC, Console, Mobile',
    description: 'Build and explore blocky worlds',
  },
  {
    id: 10,
    title: 'The Legend of Zelda: Breath of the Wild',
    genre: 'Action-adventure',
    platform: 'Switch',
    description: 'Open world adventure in Hyrule',
  },
  {
    id: 11,
    title: 'Super Mario Odyssey',
    genre: 'Platformer',
    platform: 'Switch',
    description: '3D platforming adventure with Mario',
  },
  {
    id: 12,
    title: 'Overwatch 2',
    genre: 'FPS',
    platform: 'PC, PS4, Xbox',
    description: 'Team-based multiplayer shooter',
  },
  {
    id: 13,
    title: 'God of War',
    genre: 'Action-adventure',
    platform: 'PS4',
    description: 'Norse mythology action game',
  },
  {
    id: 14,
    title: 'Slay the Spire',
    genre: 'Card game',
    platform: 'PC, Switch',
    description: 'Deck-building roguelike',
  },
  {
    id: 15,
    title: 'Dead Cells',
    genre: 'Roguelike',
    platform: 'PC, Switch',
    description: 'Metroidvania roguelike action game',
  },
  {
    id: 16,
    title: 'Cuphead',
    genre: 'Platformer',
    platform: 'PC, Switch',
    description: 'Challenging run-and-gun action game',
  },
  {
    id: 17,
    title: 'Valorant',
    genre: 'FPS',
    platform: 'PC',
    description: 'Competitive tactical shooter',
  },
  {
    id: 18,
    title: 'Fall Guys',
    genre: 'Party',
    platform: 'PC, PS4, PS5',
    description: 'Massively multiplayer mini-game competition',
  },
  {
    id: 19,
    title: 'Animal Crossing: New Horizons',
    genre: 'Simulation',
    platform: 'Switch',
    description: 'Life simulation on a deserted island',
  },
  {
    id: 20,
    title: 'Horizon Forbidden West',
    genre: 'Action RPG',
    platform: 'PS4, PS5',
    description: 'Open world RPG with robotic creatures',
  },
];
