name: Keep Render / Vercel Alive

on:
  # schedule:
  #   - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
      ROOT_URL: ${{ vars.ROOT_URL }}
    steps:
      - name: Curl health endpoint
        run: |
          curl -fsS -H "x-cron-secret: ${CRON_SECRET}" "${ROOT_URL}/api/ping" || exit 1
